package compiler

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/axsh/tokotachi/features/tt/internal/prompt/manifest"
)

// DigestInfo holds digest metadata
type DigestInfo struct {
	Digest    string `yaml:"digest"`
	Target    string `yaml:"target"`
	Timestamp string `yaml:"timestamp"`
}

// ComputeSourceDigest computes a SHA-256 digest of all source files
// defined in the project config's sources section.
func ComputeSourceDigest(cfg *manifest.ProjectConfig, rootDir string) (string, error) {
	var allFiles []string

	for _, pattern := range cfg.Sources {
		matches, err := manifest.ExpandGlob(rootDir, pattern)
		if err != nil {
			return "", fmt.Errorf("failed to expand glob %q: %w", pattern, err)
		}
		allFiles = append(allFiles, matches...)
	}

	// Convert to relative paths and deduplicate
	relPaths := make(map[string]string) // rel -> abs
	for _, absPath := range allFiles {
		rel, err := filepath.Rel(rootDir, absPath)
		if err != nil {
			return "", fmt.Errorf("failed to compute relative path for %s: %w", absPath, err)
		}
		relSlash := filepath.ToSlash(rel)
		relPaths[relSlash] = absPath
	}

	// Sort by relative path
	sortedRels := make([]string, 0, len(relPaths))
	for rel := range relPaths {
		sortedRels = append(sortedRels, rel)
	}
	sort.Strings(sortedRels)

	hasher := sha256.New()
	for _, rel := range sortedRels {
		// Write relative path
		hasher.Write([]byte(rel))
		// Write file content
		data, err := os.ReadFile(relPaths[rel])
		if err != nil {
			return "", fmt.Errorf("failed to read %s: %w", relPaths[rel], err)
		}
		hasher.Write(data)
	}

	return hex.EncodeToString(hasher.Sum(nil)), nil
}

// LoadDigest reads the previous digest from the digest file.
// Returns empty DigestInfo and nil error if file does not exist.
func LoadDigest(digestPath string) (*DigestInfo, error) {
	data, err := os.ReadFile(digestPath)
	if err != nil {
		if os.IsNotExist(err) {
			return &DigestInfo{}, nil
		}
		return nil, fmt.Errorf("failed to read digest file: %w", err)
	}

	// Strip comment lines before parsing
	var info DigestInfo
	if err := yaml.Unmarshal(data, &info); err != nil {
		return nil, fmt.Errorf("failed to parse digest file: %w", err)
	}

	return &info, nil
}

// SaveDigest writes the current digest to the digest file.
func SaveDigest(digestPath string, info *DigestInfo) error {
	dir := filepath.Dir(digestPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	if info.Timestamp == "" {
		info.Timestamp = time.Now().Format(time.RFC3339)
	}

	data, err := yaml.Marshal(info)
	if err != nil {
		return fmt.Errorf("failed to marshal digest info: %w", err)
	}

	header := "# Auto-generated by agentctl deploy. Do not edit.\n"
	content := header + string(data)

	return os.WriteFile(digestPath, []byte(content), 0644)
}

// DigestPath returns the path to the digest file for a given build dir and target.
// When target is empty or "antigravity", returns the legacy path for backward compatibility.
func DigestPath(buildDir string, target ...string) string {
	if len(target) == 0 || target[0] == "" || target[0] == "antigravity" {
		return filepath.Join(buildDir, ".compile-digest")
	}
	return filepath.Join(buildDir, ".compile-digest-"+target[0])
}
