package compiler

import (
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestWriteMetadata(t *testing.T) {
	dir := t.TempDir()
	metaDir := filepath.Join(dir, ".agent", ".meta")

	meta := &UpdateMetadata{
		UpdatedAt:    "2025-01-01T00:00:00Z",
		SourceDigest: "abc123",
		Target:       "antigravity",
	}

	err := WriteMetadata(metaDir, meta)
	require.NoError(t, err)

	// Verify file exists
	metaPath := filepath.Join(metaDir, "last_update.yaml")
	_, err = os.Stat(metaPath)
	require.NoError(t, err)

	// Verify content
	content, err := os.ReadFile(metaPath)
	require.NoError(t, err)
	assert.Contains(t, string(content), "updated_at: \"2025-01-01T00:00:00Z\"")
	assert.Contains(t, string(content), "source_digest: abc123")
	assert.Contains(t, string(content), "target: antigravity")
	assert.Contains(t, string(content), "# Auto-generated by tt prompt update")
}

func TestReadMetadata(t *testing.T) {
	dir := t.TempDir()
	metaDir := filepath.Join(dir, ".agent", ".meta")

	// Write first
	meta := &UpdateMetadata{
		UpdatedAt:    "2025-06-01T12:00:00Z",
		SourceDigest: "def456",
		Target:       "cursor",
	}
	err := WriteMetadata(metaDir, meta)
	require.NoError(t, err)

	// Read back
	got, err := ReadMetadata(metaDir)
	require.NoError(t, err)
	require.NotNil(t, got)
	assert.Equal(t, "2025-06-01T12:00:00Z", got.UpdatedAt)
	assert.Equal(t, "def456", got.SourceDigest)
	assert.Equal(t, "cursor", got.Target)
}

func TestReadMetadata_NotExists(t *testing.T) {
	dir := t.TempDir()
	metaDir := filepath.Join(dir, "nonexistent", ".meta")

	got, err := ReadMetadata(metaDir)
	require.NoError(t, err)
	assert.Nil(t, got, "should return nil when metadata does not exist")
}

func TestCheckForChanges_NoMetadata(t *testing.T) {
	// When metadata is nil, should always indicate changes
	changed := shouldUpdate(nil, false)
	assert.True(t, changed, "should update when no metadata exists")
}

func TestCheckForChanges_NoGitChanges(t *testing.T) {
	// When metadata exists and force=false, we check timestamp
	meta := &UpdateMetadata{
		UpdatedAt:    time.Now().Add(1 * time.Hour).Format(time.RFC3339),
		SourceDigest: "abc",
	}
	changed := shouldUpdate(meta, false)
	// shouldUpdate with metadata always returns false (non-force)
	// unless actual git check is done; for unit test we just test the logic
	assert.False(t, changed, "should not update when metadata exists and not forced")
}

func TestCheckForChanges_WithForce(t *testing.T) {
	meta := &UpdateMetadata{
		UpdatedAt:    time.Now().Format(time.RFC3339),
		SourceDigest: "abc",
	}
	changed := shouldUpdate(meta, true)
	assert.True(t, changed, "should update when force is true")
}

func TestCheckForChanges_NoMetadataForced(t *testing.T) {
	changed := shouldUpdate(nil, true)
	assert.True(t, changed, "should update when no metadata and force")
}
