package compiler

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestWriteMetadata(t *testing.T) {
	dir := t.TempDir()
	metaDir := filepath.Join(dir, ".agent", ".meta")

	meta := &UpdateMetadata{
		UpdatedAt:    "2025-01-01T00:00:00Z",
		SourceDigest: "abc123",
		Target:       "antigravity",
	}

	err := WriteMetadata(metaDir, meta)
	require.NoError(t, err)

	// Verify file exists
	metaPath := filepath.Join(metaDir, "last_update.yaml")
	_, err = os.Stat(metaPath)
	require.NoError(t, err)

	// Verify content
	content, err := os.ReadFile(metaPath)
	require.NoError(t, err)
	assert.Contains(t, string(content), "updated_at: \"2025-01-01T00:00:00Z\"")
	assert.Contains(t, string(content), "source_digest: abc123")
	assert.Contains(t, string(content), "target: antigravity")
	assert.Contains(t, string(content), "# Auto-generated by tt prompt update")
}

func TestReadMetadata(t *testing.T) {
	dir := t.TempDir()
	metaDir := filepath.Join(dir, ".agent", ".meta")

	// Write first
	meta := &UpdateMetadata{
		UpdatedAt:    "2025-06-01T12:00:00Z",
		SourceDigest: "def456",
		Target:       "cursor",
	}
	err := WriteMetadata(metaDir, meta)
	require.NoError(t, err)

	// Read back
	got, err := ReadMetadata(metaDir)
	require.NoError(t, err)
	require.NotNil(t, got)
	assert.Equal(t, "2025-06-01T12:00:00Z", got.UpdatedAt)
	assert.Equal(t, "def456", got.SourceDigest)
	assert.Equal(t, "cursor", got.Target)
}

func TestReadMetadata_NotExists(t *testing.T) {
	dir := t.TempDir()
	metaDir := filepath.Join(dir, "nonexistent", ".meta")

	got, err := ReadMetadata(metaDir)
	require.NoError(t, err)
	assert.Nil(t, got, "should return nil when metadata does not exist")
}

func TestCheckForChanges_NoMetadata(t *testing.T) {
	// When metadata is nil, should always indicate changes
	changed := shouldUpdate(nil, false)
	assert.True(t, changed, "should update when no metadata exists")
}

func TestCheckForChanges_NoGitChanges(t *testing.T) {
	// When metadata exists and force=false, we check timestamp
	meta := &UpdateMetadata{
		UpdatedAt:    time.Now().Add(1 * time.Hour).Format(time.RFC3339),
		SourceDigest: "abc",
	}
	changed := shouldUpdate(meta, false)
	// shouldUpdate with metadata always returns false (non-force)
	// unless actual git check is done; for unit test we just test the logic
	assert.False(t, changed, "should not update when metadata exists and not forced")
}

func TestCheckForChanges_WithForce(t *testing.T) {
	meta := &UpdateMetadata{
		UpdatedAt:    time.Now().Format(time.RFC3339),
		SourceDigest: "abc",
	}
	changed := shouldUpdate(meta, true)
	assert.True(t, changed, "should update when force is true")
}

func TestCheckForChanges_NoMetadataForced(t *testing.T) {
	changed := shouldUpdate(nil, true)
	assert.True(t, changed, "should update when no metadata and force")
}

func TestUpdate_Drift(t *testing.T) {
	tmpDir := t.TempDir()
	copyTestdata(t, filepath.Join("testdata", "valid"), tmpDir)

	// Initialize git repo to make CheckForChanges happy
	cmdInit := exec.Command("git", "init")
	cmdInit.Dir = tmpDir
	err := cmdInit.Run()
	require.NoError(t, err)

	cmdConfigName := exec.Command("git", "config", "user.name", "test")
	cmdConfigName.Dir = tmpDir
	_ = cmdConfigName.Run()

	cmdConfigEmail := exec.Command("git", "config", "user.email", "test@test.com")
	cmdConfigEmail.Dir = tmpDir
	_ = cmdConfigEmail.Run()

	cmdAdd := exec.Command("git", "add", ".")
	cmdAdd.Dir = tmpDir
	err = cmdAdd.Run()
	require.NoError(t, err)

	cmdCommit := exec.Command("git", "commit", "-m", "initial")
	cmdCommit.Dir = tmpDir
	err = cmdCommit.Run()
	require.NoError(t, err)

	// Sleep to ensure commit timestamp is strictly in the past relative to first Update's metadata
	time.Sleep(2 * time.Second)

	projectPath := filepath.Join(tmpDir, "prompts", "manifest", "project.yaml")

	// 1. First update (should run deploy)
	res1, err := Update(UpdateOptions{
		ProjectPath: projectPath,
		Target:      "antigravity",
		Force:       false,
		DryRun:      false,
	})
	require.NoError(t, err)
	require.NotNil(t, res1)
	require.Contains(t, res1.TargetResults, "antigravity")
	assert.False(t, res1.TargetResults["antigravity"].Skipped)

	// Verify target file was created
	targetFile := filepath.Join(tmpDir, ".agents", "rules", "test-compile-policy.md")
	_, err = os.Stat(targetFile)
	require.NoError(t, err)

	// Wait 1 second to ensure updatedAt in metadata is strictly in the past
	time.Sleep(1 * time.Second)

	// 2. Second update (should skip since no changes and no drift)
	res2, err := Update(UpdateOptions{
		ProjectPath: projectPath,
		Target:      "antigravity",
		Force:       false,
		DryRun:      false,
	})
	require.NoError(t, err)
	require.NotNil(t, res2)
	assert.True(t, res2.TargetResults["antigravity"].Skipped)

	// 3. Delete target file to introduce drift
	err = os.Remove(targetFile)
	require.NoError(t, err)

	// 4. Third update (should deploy because drift was detected)
	res3, err := Update(UpdateOptions{
		ProjectPath: projectPath,
		Target:      "antigravity",
		Force:       false,
		DryRun:      false,
	})
	require.NoError(t, err)
	require.NotNil(t, res3)
	assert.False(t, res3.TargetResults["antigravity"].Skipped)

	// Verify target file was recreated
	_, err = os.Stat(targetFile)
	require.NoError(t, err)
}
