package compiler

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestWriteMetadata(t *testing.T) {
	dir := t.TempDir()
	metaDir := filepath.Join(dir, ".agent", ".meta")

	meta := &UpdateMetadata{
		UpdatedAt:    "2025-01-01T00:00:00Z",
		SourceDigest: "abc123",
		Target:       "antigravity",
	}

	err := WriteMetadata(metaDir, meta)
	require.NoError(t, err)

	// Verify file exists
	metaPath := filepath.Join(metaDir, "last_update.yaml")
	_, err = os.Stat(metaPath)
	require.NoError(t, err)

	// Verify content
	content, err := os.ReadFile(metaPath)
	require.NoError(t, err)
	assert.Contains(t, string(content), "updated_at: \"2025-01-01T00:00:00Z\"")
	assert.Contains(t, string(content), "source_digest: abc123")
	assert.Contains(t, string(content), "target: antigravity")
	assert.Contains(t, string(content), "# Auto-generated by tt prompt update")
}

func TestReadMetadata(t *testing.T) {
	dir := t.TempDir()
	metaDir := filepath.Join(dir, ".agent", ".meta")

	// Write first
	meta := &UpdateMetadata{
		UpdatedAt:    "2025-06-01T12:00:00Z",
		SourceDigest: "def456",
		Target:       "cursor",
	}
	err := WriteMetadata(metaDir, meta)
	require.NoError(t, err)

	// Read back
	got, err := ReadMetadata(metaDir)
	require.NoError(t, err)
	require.NotNil(t, got)
	assert.Equal(t, "2025-06-01T12:00:00Z", got.UpdatedAt)
	assert.Equal(t, "def456", got.SourceDigest)
	assert.Equal(t, "cursor", got.Target)
}

func TestReadMetadata_NotExists(t *testing.T) {
	dir := t.TempDir()
	metaDir := filepath.Join(dir, "nonexistent", ".meta")

	got, err := ReadMetadata(metaDir)
	require.NoError(t, err)
	assert.Nil(t, got, "should return nil when metadata does not exist")
}

func TestCheckForChanges_NoMetadata(t *testing.T) {
	// When metadata is nil, should always indicate changes
	changed := shouldUpdate(nil, false)
	assert.True(t, changed, "should update when no metadata exists")
}

func TestCheckForChanges_NoGitChanges(t *testing.T) {
	// When metadata exists and force=false, we check timestamp
	meta := &UpdateMetadata{
		UpdatedAt:    time.Now().Add(1 * time.Hour).Format(time.RFC3339),
		SourceDigest: "abc",
	}
	changed := shouldUpdate(meta, false)
	// shouldUpdate with metadata always returns false (non-force)
	// unless actual git check is done; for unit test we just test the logic
	assert.False(t, changed, "should not update when metadata exists and not forced")
}

func TestCheckForChanges_WithForce(t *testing.T) {
	meta := &UpdateMetadata{
		UpdatedAt:    time.Now().Format(time.RFC3339),
		SourceDigest: "abc",
	}
	changed := shouldUpdate(meta, true)
	assert.True(t, changed, "should update when force is true")
}

func TestCheckForChanges_NoMetadataForced(t *testing.T) {
	changed := shouldUpdate(nil, true)
	assert.True(t, changed, "should update when no metadata and force")
}

func TestUpdate_Drift(t *testing.T) {
	tmpDir := t.TempDir()
	copyTestdata(t, filepath.Join("testdata", "valid"), tmpDir)

	// Initialize git repo to make CheckForChanges happy
	cmdInit := exec.Command("git", "init")
	cmdInit.Dir = tmpDir
	err := cmdInit.Run()
	require.NoError(t, err)

	cmdConfigName := exec.Command("git", "config", "user.name", "test")
	cmdConfigName.Dir = tmpDir
	_ = cmdConfigName.Run()

	cmdConfigEmail := exec.Command("git", "config", "user.email", "test@test.com")
	cmdConfigEmail.Dir = tmpDir
	_ = cmdConfigEmail.Run()

	cmdAdd := exec.Command("git", "add", ".")
	cmdAdd.Dir = tmpDir
	err = cmdAdd.Run()
	require.NoError(t, err)

	cmdCommit := exec.Command("git", "commit", "-m", "initial")
	cmdCommit.Dir = tmpDir
	err = cmdCommit.Run()
	require.NoError(t, err)

	// Sleep to ensure commit timestamp is strictly in the past relative to first Update's metadata
	time.Sleep(2 * time.Second)

	projectPath := filepath.Join(tmpDir, "prompts", "manifest", "project.yaml")

	// 1. First update (should run deploy)
	res1, err := Update(UpdateOptions{
		ProjectPath: projectPath,
		Target:      "antigravity",
		Force:       false,
		DryRun:      false,
	})
	require.NoError(t, err)
	require.NotNil(t, res1)
	require.Contains(t, res1.TargetResults, "antigravity")
	assert.False(t, res1.TargetResults["antigravity"].Skipped)

	// Verify target file was created
	targetFile := filepath.Join(tmpDir, ".agent", "rules", "test-compile-policy.md")
	_, err = os.Stat(targetFile)
	require.NoError(t, err)

	// Wait 1 second to ensure updatedAt in metadata is strictly in the past
	time.Sleep(1 * time.Second)

	// 2. Second update (should skip since no changes and no drift)
	res2, err := Update(UpdateOptions{
		ProjectPath: projectPath,
		Target:      "antigravity",
		Force:       false,
		DryRun:      false,
	})
	require.NoError(t, err)
	require.NotNil(t, res2)
	assert.True(t, res2.TargetResults["antigravity"].Skipped)

	// 3. Delete target file to introduce drift
	err = os.Remove(targetFile)
	require.NoError(t, err)

	// 4. Third update (should deploy because drift was detected)
	res3, err := Update(UpdateOptions{
		ProjectPath: projectPath,
		Target:      "antigravity",
		Force:       false,
		DryRun:      false,
	})
	require.NoError(t, err)
	require.NotNil(t, res3)
	assert.False(t, res3.TargetResults["antigravity"].Skipped)

	// Verify target file was recreated
	_, err = os.Stat(targetFile)
	require.NoError(t, err)
}

// initGitRepo initializes a git repo in the given directory for testing.
func initGitRepo(t *testing.T, dir string) {
	t.Helper()
	cmds := [][]string{
		{"git", "init"},
		{"git", "config", "user.name", "test"},
		{"git", "config", "user.email", "test@test.com"},
		{"git", "add", "."},
		{"git", "commit", "-m", "initial"},
	}
	for _, args := range cmds {
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = dir
		if err := cmd.Run(); err != nil {
			t.Fatalf("git command %v failed: %v", args, err)
		}
	}
}

func TestUpdate_ValidationErrors_ReturnsError(t *testing.T) {
	tmpDir := t.TempDir()
	copyTestdata(t, filepath.Join("testdata", "invalid_target"), tmpDir)

	initGitRepo(t, tmpDir)

	projectPath := filepath.Join(tmpDir, "prompts", "manifest", "project.yaml")

	_, err := Update(UpdateOptions{
		ProjectPath: projectPath,
		Target:      "antigravity",
		Force:       true,
	})
	require.Error(t, err, "Update should return error when validation fails")
	assert.Contains(t, err.Error(), "validation error")

	// Verify metadata was NOT written
	metaDir := filepath.Join(tmpDir, ".agent", ".meta", "antigravity")
	_, statErr := os.Stat(filepath.Join(metaDir, "last_update.yaml"))
	assert.True(t, os.IsNotExist(statErr),
		"metadata should not be written when validation errors exist")
}

func TestUpdate_CatalogTemplate_AllTargets(t *testing.T) {
	tmpDir := t.TempDir()
	copyTestdata(t, filepath.Join("testdata", "catalog_template"), tmpDir)

	initGitRepo(t, tmpDir)

	projectPath := filepath.Join(tmpDir, "prompts", "manifest", "project.yaml")

	tests := []struct {
		target    string
		rulesDir  string
		skillsDir string
		metaDir   string
	}{
		{
			target:    "antigravity",
			rulesDir:  ".agent/rules",
			skillsDir: ".agent/skills",
			metaDir:   ".agent/.meta/antigravity",
		},
		{
			target:    "codex",
			rulesDir:  ".codex/rules",
			skillsDir: ".codex/skills",
			metaDir:   ".codex/.meta",
		},
		{
			target:    "claude-code",
			rulesDir:  ".claude/rules",
			skillsDir: ".claude/skills",
			metaDir:   ".claude/.meta",
		},
		{
			target:    "cursor",
			rulesDir:  ".cursor/rules",
			skillsDir: ".cursor/skills",
			metaDir:   ".cursor/.meta",
		},
	}

	for _, tt := range tests {
		t.Run(tt.target, func(t *testing.T) {
			result, err := Update(UpdateOptions{
				ProjectPath: projectPath,
				Target:      tt.target,
				Force:       true,
			})
			require.NoError(t, err, "Update should succeed for target %s", tt.target)
			require.NotNil(t, result)
			require.Contains(t, result.TargetResults, tt.target)
			assert.False(t, result.TargetResults[tt.target].Skipped)

			// Verify rules directory contains files
			rulesPath := filepath.Join(tmpDir, tt.rulesDir)
			entries, err := os.ReadDir(rulesPath)
			require.NoError(t, err,
				"rules directory %s should exist for target %s", tt.rulesDir, tt.target)
			assert.Greater(t, len(entries), 0,
				"rules directory should contain files for target %s", tt.target)

			// Verify skills directory contains files
			skillsPath := filepath.Join(tmpDir, tt.skillsDir)
			entries, err = os.ReadDir(skillsPath)
			require.NoError(t, err,
				"skills directory %s should exist for target %s", tt.skillsDir, tt.target)
			assert.Greater(t, len(entries), 0,
				"skills directory should contain files for target %s", tt.target)

			// Verify metadata was written to the correct path
			metaPath := filepath.Join(tmpDir, tt.metaDir, "last_update.yaml")
			_, err = os.Stat(metaPath)
			require.NoError(t, err,
				"metadata should exist at %s for target %s", tt.metaDir, tt.target)
		})
	}

	// Verify .agents/ directory does NOT exist
	agentsPath := filepath.Join(tmpDir, ".agents")
	_, err := os.Stat(agentsPath)
	assert.True(t, os.IsNotExist(err),
		".agents/ directory should NOT exist (metadata should be in target-specific dirs)")
}
