package memory

import (
	"strings"
	"testing"

	"github.com/axsh/tokotachi/features/tt/internal/prompt/manifest"
)

func TestGenerateIndex(t *testing.T) {
	docs := []*manifest.MemoryDoc{
		{
			ID:           "current-overview",
			Title:        "Current Architecture Overview",
			Status:       "current",
			Topics:       []string{"overview", "modules"},
			Triggers:     []string{"understanding project structure"},
			LastReviewed: "2026-06-04",
			FilePath:     "prompts/memory/current.md",
		},
		{
			ID:       "invariants",
			Title:    "Invariants",
			Status:   "current",
			Topics:   []string{"constraints"},
			Triggers: []string{"making design changes"},
			FilePath: "prompts/memory/invariants.md",
		},
		{
			ID:           "decisions",
			Title:        "Decisions",
			Status:       "current",
			Topics:       []string{"adr"},
			Triggers:     []string{"reviewing past decisions"},
			LastReviewed: "2026-05-30",
			FilePath:     "prompts/memory/decisions.md",
		},
	}

	result, err := GenerateIndex(docs)
	if err != nil {
		t.Fatalf("GenerateIndex() error = %v", err)
	}

	// Generated banner (MUST)
	if !strings.Contains(result, "GENERATED FILE -- DO NOT EDIT") {
		t.Error("missing generated file banner")
	}
	if !strings.Contains(result, "Source digest:") {
		t.Error("missing source digest")
	}
	if !strings.Contains(result, "Generated by: agentctl compile") {
		t.Error("missing generator attribution")
	}

	// Heading
	if !strings.Contains(result, "# Project Memory Route Map") {
		t.Error("missing main heading")
	}

	// Routing table header with Last Reviewed (MUST)
	if !strings.Contains(result, "| ID | Path | Status | Topics | Read When | Last Reviewed |") {
		t.Error("missing routing table header with Last Reviewed column")
	}

	// Last Reviewed values
	if !strings.Contains(result, "2026-06-04") {
		t.Error("missing last_reviewed value 2026-06-04 for current-overview")
	}
	if !strings.Contains(result, "2026-05-30") {
		t.Error("missing last_reviewed value 2026-05-30 for decisions")
	}
	// invariants has no last_reviewed, should show "-"
	// Find the invariants row and check it contains " - |"
	lines := strings.Split(result, "\n")
	for _, line := range lines {
		if strings.Contains(line, "| invariants |") {
			if !strings.Contains(line, "| - |") {
				t.Errorf("invariants row should show '-' for missing last_reviewed, got: %s", line)
			}
			break
		}
	}

	// Each document must appear in the table
	if !strings.Contains(result, "current-overview") {
		t.Error("missing current-overview entry")
	}
	if !strings.Contains(result, "invariants") {
		t.Error("missing invariants entry")
	}
	if !strings.Contains(result, "decisions") {
		t.Error("missing decisions entry")
	}

	// Fallback (MUST)
	if !strings.Contains(result, "inbox.md") {
		t.Error("missing fallback reference to inbox.md")
	}
	if !strings.Contains(result, "open-questions.md") {
		t.Error("missing fallback reference to open-questions.md")
	}

	// Update Rules (MUST)
	if !strings.Contains(result, "## Update Rules") {
		t.Error("missing Update Rules section")
	}
	if !strings.Contains(result, "Do not invent architecture") {
		t.Error("missing 'Do not invent architecture' rule")
	}
	if !strings.Contains(result, "inbox.md") {
		t.Error("missing inbox fallback rule")
	}
	if !strings.Contains(result, "scripts/prompt/deploy.sh") {
		t.Error("missing recompile instruction")
	}
	if !strings.Contains(result, "open-questions.md") {
		t.Error("missing open-questions rule")
	}
}

func TestGenerateIndex_ReadingOrder(t *testing.T) {
	docs := []*manifest.MemoryDoc{
		{ID: "z-doc", Title: "Z Doc", Status: "current", FilePath: "prompts/memory/z-doc.md"},
		{ID: "current-overview", Title: "Current", Status: "current", FilePath: "prompts/memory/current.md"},
		{ID: "invariants", Title: "Invariants", Status: "current", FilePath: "prompts/memory/invariants.md"},
		{ID: "decisions", Title: "Decisions", Status: "current", FilePath: "prompts/memory/decisions.md"},
	}

	result, err := GenerateIndex(docs)
	if err != nil {
		t.Fatalf("GenerateIndex() error = %v", err)
	}

	// Verify reading order section places current.md before invariants.md before decisions.md
	lines := strings.Split(result, "\n")
	var orderLines []string
	inOrder := false
	for _, line := range lines {
		if strings.Contains(line, "## Recommended Reading Order") {
			inOrder = true
			continue
		}
		if inOrder && strings.HasPrefix(line, "## ") {
			break
		}
		if inOrder && strings.Contains(line, "./") {
			orderLines = append(orderLines, line)
		}
	}

	if len(orderLines) < 3 {
		t.Fatalf("expected at least 3 order lines, got %d", len(orderLines))
	}
	// current.md should be first
	if !strings.Contains(orderLines[0], "current.md") {
		t.Errorf("first reading order entry should be current.md, got: %s", orderLines[0])
	}
	// invariants.md should be second
	if !strings.Contains(orderLines[1], "invariants.md") {
		t.Errorf("second reading order entry should be invariants.md, got: %s", orderLines[1])
	}
	// decisions.md should be third
	if !strings.Contains(orderLines[2], "decisions.md") {
		t.Errorf("third reading order entry should be decisions.md, got: %s", orderLines[2])
	}
}

func TestGenerateIndex_EmptyDocs(t *testing.T) {
	result, err := GenerateIndex([]*manifest.MemoryDoc{})
	if err != nil {
		t.Fatalf("GenerateIndex() error = %v", err)
	}
	if !strings.Contains(result, "GENERATED FILE -- DO NOT EDIT") {
		t.Error("empty docs should still produce banner")
	}
}

func TestComputeDigest(t *testing.T) {
	docs := []*manifest.MemoryDoc{
		{ID: "a", Status: "current", Title: "A", Topics: []string{"t1"}},
	}
	d1 := computeDigest(docs)
	if d1 == "" {
		t.Error("computeDigest() returned empty string")
	}
	if !strings.HasPrefix(d1, "sha256:") {
		t.Errorf("computeDigest() should start with sha256:, got %q", d1)
	}

	// Same input should produce same digest
	d2 := computeDigest(docs)
	if d1 != d2 {
		t.Errorf("computeDigest() not deterministic: %q != %q", d1, d2)
	}

	// Different input should produce different digest
	docs2 := []*manifest.MemoryDoc{
		{ID: "b", Status: "current", Title: "B", Topics: []string{"t2"}},
	}
	d3 := computeDigest(docs2)
	if d1 == d3 {
		t.Error("computeDigest() should differ for different inputs")
	}
}
