package memory

import (
	"crypto/sha256"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/axsh/tokotachi/features/tt/internal/prompt/manifest"
)

// priorityOrder defines the preferred reading order for current documents
var priorityOrder = []string{"current.md", "invariants.md", "decisions.md"}

// GenerateIndex generates the content of index.md from a list of MemoryDocs
func GenerateIndex(docs []*manifest.MemoryDoc) (string, error) {
	var b strings.Builder

	digest := computeDigest(docs)

	// 1. Generated banner (MUST)
	b.WriteString("<!-- GENERATED FILE -- DO NOT EDIT -->\n")
	b.WriteString(fmt.Sprintf("<!-- Source digest: %s -->\n", digest))
	b.WriteString("<!-- Generated by: agentctl compile -->\n")
	b.WriteString("\n")

	// 2. Heading
	b.WriteString("# Project Memory Route Map\n")
	b.WriteString("\n")

	// 3. Recommended reading order (MUST) - current status docs in priority order
	b.WriteString("## Recommended Reading Order\n")
	b.WriteString("\n")
	b.WriteString("For new contributors, read documents in this order:\n")
	b.WriteString("\n")

	currentDocs := filterByStatus(docs, "current")
	ordered := sortByPriority(currentDocs)
	for i, doc := range ordered {
		relPath := toRelativePath(doc.FilePath)
		b.WriteString(fmt.Sprintf("%d. [%s](%s)\n", i+1, doc.Title, relPath))
	}
	b.WriteString("\n")

	// 4. Routing table (MUST)
	b.WriteString("## Document Routing Table\n")
	b.WriteString("\n")
	b.WriteString("| ID | Path | Status | Topics | Read When | Last Reviewed |\n")
	b.WriteString("|:---|:-----|:-------|:-------|:----------|:-------------|\n")

	// Sort all docs alphabetically by ID for stable output
	sortedDocs := make([]*manifest.MemoryDoc, len(docs))
	copy(sortedDocs, docs)
	sort.Slice(sortedDocs, func(i, j int) bool {
		return sortedDocs[i].ID < sortedDocs[j].ID
	})

	for _, doc := range sortedDocs {
		relPath := toRelativePath(doc.FilePath)
		topics := strings.Join(doc.Topics, ", ")
		triggers := strings.Join(doc.Triggers, ", ")
		lastReviewed := doc.LastReviewed
		if lastReviewed == "" {
			lastReviewed = "-"
		}
		b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s |\n",
			doc.ID, relPath, doc.Status, topics, triggers, lastReviewed))
	}
	b.WriteString("\n")

	// 5. Fallback (MUST)
	b.WriteString("## Fallback\n")
	b.WriteString("\n")
	b.WriteString("If no document above matches your need:\n")
	b.WriteString("\n")
	b.WriteString("- Check [inbox.md](./inbox.md) for unclassified design memos\n")
	b.WriteString("- Check [open-questions.md](./open-questions.md) for unresolved design questions\n")
	b.WriteString("\n")

	// 6. Update Rules (MUST)
	b.WriteString("## Update Rules\n")
	b.WriteString("\n")
	b.WriteString("When updating memory documents, follow these rules:\n")
	b.WriteString("\n")
	b.WriteString("- Do not invent architecture. Document what exists or what was decided.\n")
	b.WriteString("- If you cannot classify a piece of information, write it to [inbox.md](./inbox.md).\n")
	b.WriteString("- After adding a new memory document or changing frontmatter, recompile the index by running `./scripts/prompt/deploy.sh --force`.\n")
	b.WriteString("- If a design decision changed, update or create an ADR in `adr/`.\n")
	b.WriteString("- If unclear, write to [open-questions.md](./open-questions.md) rather than making assumptions.\n")

	return b.String(), nil
}

// computeDigest computes a SHA-256 digest from all MemoryDoc metadata
func computeDigest(docs []*manifest.MemoryDoc) string {
	var parts []string
	for _, doc := range docs {
		part := fmt.Sprintf("%s|%s|%s|%s", doc.ID, doc.Status, doc.Title, strings.Join(doc.Topics, ","))
		parts = append(parts, part)
	}
	sort.Strings(parts)
	combined := strings.Join(parts, "\n")
	hash := sha256.Sum256([]byte(combined))
	return fmt.Sprintf("sha256:%x", hash)
}

// filterByStatus returns docs with the given status
func filterByStatus(docs []*manifest.MemoryDoc, status string) []*manifest.MemoryDoc {
	var result []*manifest.MemoryDoc
	for _, doc := range docs {
		if doc.Status == status {
			result = append(result, doc)
		}
	}
	return result
}

// sortByPriority sorts current docs by the priority order, then alphabetically
func sortByPriority(docs []*manifest.MemoryDoc) []*manifest.MemoryDoc {
	result := make([]*manifest.MemoryDoc, len(docs))
	copy(result, docs)

	priorityMap := make(map[string]int)
	for i, name := range priorityOrder {
		priorityMap[name] = i
	}

	sort.SliceStable(result, func(i, j int) bool {
		filenameI := filepath.Base(result[i].FilePath)
		filenameJ := filepath.Base(result[j].FilePath)
		priI, okI := priorityMap[filenameI]
		priJ, okJ := priorityMap[filenameJ]

		if okI && okJ {
			return priI < priJ
		}
		if okI {
			return true // priority docs come first
		}
		if okJ {
			return false
		}
		return filenameI < filenameJ // alphabetical for non-priority
	})

	return result
}

// toRelativePath converts a file path to a ./ relative path
func toRelativePath(path string) string {
	base := filepath.Base(path)
	return "./" + base
}
